### ISSUE TITLE
2.0.4 not working 

### ISSUE THREAD

**Issue by arvenom** [SchumacherFM/Magento2-Pace#2]
doesnt load on CE 2.0.4 and when I try to run the compiler I get a bunch of errors 

`````` SchumacherFM\Pace\Block\Plugin\AbstractPace
        Incorrect dependency in class SchumacherFM\Pace\Block\Plugin\AbstractPace in /Applications/MAMP/htdocs/theil/htdocs/vendor/schumacherfm/mage2-pace/Block/Plugin/AbstractPace.php```
``````

**Comment by devdesco-ceo** [comment]
not using compiler on 2.0.4
backend loads fine but not all themes though. frontend does not work at all. please fix it!

**Comment by SchumacherFM** [comment]
Any chance to send me a pull request and fix this error?

**Comment by devdesco-ceo** [comment]
don't mind. I am using the Pace without your module. It took me 2 minutes to integrate the pace.js and .css file into my M2 setup.

**Comment by SchumacherFM** [comment]
Frontend was never implemented.

**Comment by ramantalkin** [comment]
@viktor-zhuromskyy i am also trying to do the same using https://github.com/ercling/yii2-pace
could you please help me out . how you did that.

@SchumacherFM it is still showing 'requires php5.6' error when running on php7

**Comment by SchumacherFM** [comment]
Closing. Stealth issue. Also updated this module to 0.2.1
