### ISSUE TITLE
Installation on 2.1.1

### ISSUE THREAD

**Issue by Kroellie** [SchumacherFM/Magento2-Pace#3]
After following installation instructions on M2.1.1, and executing composer update:

Loading composer repositories with package information
Updating dependencies (including require-dev)  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package schumacher/mage2-pace could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

When changing to version 0.1.0 a PHP 7 support error is shown. Could you please assist?

Also a question: Am I understanding it correctly if this is only for the backend, and not for the frontend?

Thx

**Comment by SchumacherFM** [comment]
I have never tested it with M2 > 2.0.2

if you send me a pull request to fix it for M2.1 I'm happy to merge it!

This package is only for the backend.

**Comment by SchumacherFM** [comment]
fixed
