### ISSUE TITLE
class SchumacherFM\Pace\Block\Plugin\Backend\Page\RequireJs doesn't exist

### ISSUE THREAD

**Issue by mvistas** [SchumacherFM/Magento2-Pace#4]
I am working with Magento 2.0.7 and I am getting this error:
class SchumacherFM\Pace\Block\Plugin\Backend\Page\RequireJs doesn't exist

any clue?

Best Regards

**Comment by SchumacherFM** [comment]
Ah yes, that has been maybe refactored. Can you send me a pull request to fix this issue?

**Comment by mvistas** [comment]
It is a client project, can send you a pull request. Sorry.
Any other way to fix this?

**Comment by SchumacherFM** [comment]
Nope. It must be refactored.

**Comment by mvistas** [comment]
It is instaled without errors!
thank you
