### ISSUE TITLE
How to make it work on frontend on Custom theme.

### ISSUE THREAD

**Issue by vinaykumar9999** [SchumacherFM/Magento2-Pace#5]
Hi

I have implemented in Magento 2.2.2 without any Errors. Working fine on Magento 2.2.2  Backend but not working on frontend. I have selected the correct configuration for frontend but Pace is not showing up in frontend. Do i need to write custom css for make it work on frontend custom theme. If so could you please suggest the class( A General Class) which i need to add in custom css

Best Regards

**Comment by SchumacherFM** [comment]
Hi,

i've never implemented it for the frontend. So it does not work. But you can send me a pull request with your code changes.

Cheers

**Comment by vinaykumar9999** [comment]
Hi

To make it work on frontend of custom theme -
I have created new folders in the module - 

app/code/SchumacherFM/Pace/view/frontend/web/css/pace-theme-minimal.css

app/code/SchumacherFM/Pace/view/frontend/web/js/pace/pace.min.js

I have called the above two in default.xml of the theme by the following code.

	<head>
		
		
		<css src="SchumacherFM_Pace::css/pace-theme-minimal.css" />
		
		
		
		<script src="SchumacherFM_Pace::js/pace/pace.min.js" />
		
	</head>

Cheers :)

**Comment by codemastering** [comment]
@vinaykumar9999  Thank you so much. It worked!!! 💯

**Comment by rav-redchamps** [comment]
@SchumacherFM added a pull request to fix this issue/feature request. Kindly review and process if everything seems fine.

**Comment by SchumacherFM** [comment]
Thank you!
